GET http://localhost:5285/api/Notes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibm90ZXRha2VyIiwiZXhwIjoxNzgwMTMxNzQ2LCJpc3MiOiJTZWN1cmVOb3RlQVBJIiwiYXVkIjoiU2VjdXJlTm90ZUFQSSJ9.wOuVeyZQKVmpDUt5e_Ww8_jl0CGzpAtYVdFvDx9oaXM